import { Layer, GradientState } from './gradient-utils';

export interface GradientTemplate {
  id: string;
  name: string;
  layers: Omit<Layer, 'id'>[];
}

export const GRADIENT_TEMPLATES: GradientTemplate[] = [
  {
    id: 'sunset-vibes',
    name: 'Sunset Vibes',
    layers: [
      {
        name: 'Sun Glow',
        type: 'gradient',
        gradient: {
          type: 'radial',
          angle: 90,
          stops: [
            { id: 's1', color: '#ff8c00', position: 0, opacity: 0.8 },
            { id: 's2', color: '#ff4500', position: 100, opacity: 0 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 80,
          radialY: 20,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 0.8,
        visible: true,
        blurEnabled: true,
        blurAmount: 20,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'screen',
      },
      {
        name: 'Sky Gradient',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 180,
          stops: [
            { id: 's3', color: '#2c3e50', position: 0, opacity: 1 },
            { id: 's4', color: '#fd746c', position: 100, opacity: 1 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
    ],
  },
  {
    id: 'aurora-borealis',
    name: 'Aurora Borealis',
    layers: [
      {
        name: 'Green Wave',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 45,
          stops: [
            { id: 'a1', color: '#00ff00', position: 0, opacity: 0 },
            { id: 'a2', color: '#00ff00', position: 50, opacity: 0.5 },
            { id: 'a3', color: '#00ff00', position: 100, opacity: 0 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 0.6,
        visible: true,
        blurEnabled: true,
        blurAmount: 40,
        noiseEnabled: true,
        noiseAmount: 30,
        blendMode: 'screen',
      },
      {
        name: 'Deep Space',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 0,
          stops: [
            { id: 'a4', color: '#000000', position: 0, opacity: 1 },
            { id: 'a5', color: '#0f0c29', position: 100, opacity: 1 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
    ],
  },
  {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    layers: [
      {
        name: 'Neon Pink',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 135,
          stops: [
            { id: 'c1', color: '#ff00ff', position: 0, opacity: 1 },
            { id: 'c2', color: '#00ffff', position: 100, opacity: 1 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 0.8,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: true,
        noiseAmount: 10,
        blendMode: 'overlay',
      },
      {
        name: 'Dark Base',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 0,
          stops: [
            { id: 'c3', color: '#1a1a1a', position: 0, opacity: 1 },
            { id: 'c4', color: '#4b0082', position: 100, opacity: 1 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
    ],
  },
  {
    id: 'mesh-candy',
    name: 'Cotton Candy',
    layers: [
      {
        name: 'Pink Blob',
        type: 'gradient',
        gradient: {
          type: 'radial',
          angle: 0,
          stops: [
            { id: 'm1', color: '#ffafbd', position: 0, opacity: 0.8 },
            { id: 'm2', color: '#ffafbd', position: 100, opacity: 0 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 20,
          radialY: 20,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: true,
        blurAmount: 50,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
      {
        name: 'Blue Blob',
        type: 'gradient',
        gradient: {
          type: 'radial',
          angle: 0,
          stops: [
            { id: 'm3', color: '#2193b0', position: 0, opacity: 0.8 },
            { id: 'm4', color: '#2193b0', position: 100, opacity: 0 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 80,
          radialY: 80,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: true,
        blurAmount: 50,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
      {
        name: 'Base White',
        type: 'color',
        color: '#ffffff',
        opacity: 1,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
    ],
  },
  {
    id: 'tropical-paradise',
    name: 'Tropical Paradise',
    layers: [
      {
        name: 'Sunlight',
        type: 'gradient',
        gradient: {
          type: 'radial',
          angle: 0,
          stops: [
            { id: 't1', color: '#fff9c4', position: 0, opacity: 0.6 },
            { id: 't2', color: '#fff9c4', position: 100, opacity: 0 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 10,
          radialY: 10,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 0.8,
        visible: true,
        blurEnabled: true,
        blurAmount: 30,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'screen',
      },
      {
        name: 'Water',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 180,
          stops: [
            { id: 't3', color: '#00bcd4', position: 0, opacity: 1 },
            { id: 't4', color: '#009688', position: 100, opacity: 1 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: true,
        noiseAmount: 15,
        blendMode: 'normal',
      },
    ],
  },
  {
    id: 'space-nebula',
    name: 'Space Nebula',
    layers: [
      {
        name: 'Purple Mist',
        type: 'gradient',
        gradient: {
          type: 'radial',
          angle: 0,
          stops: [
            { id: 'n1', color: '#9c27b0', position: 0, opacity: 0.4 },
            { id: 'n2', color: '#9c27b0', position: 100, opacity: 0 },
          ],
          radialShape: 'ellipse',
          radialSize: 'farthest-corner',
          radialX: 30,
          radialY: 40,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 0.7,
        visible: true,
        blurEnabled: true,
        blurAmount: 60,
        noiseEnabled: true,
        noiseAmount: 40,
        blendMode: 'screen',
      },
      {
        name: 'Blue Mist',
        type: 'gradient',
        gradient: {
          type: 'radial',
          angle: 0,
          stops: [
            { id: 'n3', color: '#03a9f4', position: 0, opacity: 0.4 },
            { id: 'n4', color: '#03a9f4', position: 100, opacity: 0 },
          ],
          radialShape: 'ellipse',
          radialSize: 'farthest-corner',
          radialX: 70,
          radialY: 60,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 0.7,
        visible: true,
        blurEnabled: true,
        blurAmount: 60,
        noiseEnabled: true,
        noiseAmount: 40,
        blendMode: 'screen',
      },
      {
        name: 'Deep Space',
        type: 'color',
        color: '#050505',
        opacity: 1,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
    ],
  },
  {
    id: 'golden-hour',
    name: 'Golden Hour',
    layers: [
      {
        name: 'Glow',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 90,
          stops: [
            { id: 'g1', color: '#ffd700', position: 0, opacity: 0.5 },
            { id: 'g2', color: '#ff8c00', position: 100, opacity: 0.5 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: true,
        blurAmount: 10,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'overlay',
      },
      {
        name: 'Base',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 180,
          stops: [
            { id: 'g3', color: '#ff5f6d', position: 0, opacity: 1 },
            { id: 'g4', color: '#ffc371', position: 100, opacity: 1 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
    ],
  },
  {
    id: 'electric-blue',
    name: 'Electric Blue',
    layers: [
      {
        name: 'Spark',
        type: 'gradient',
        gradient: {
          type: 'conic',
          angle: 0,
          stops: [
            { id: 'e1', color: '#00ffff', position: 0, opacity: 1 },
            { id: 'e2', color: '#0000ff', position: 50, opacity: 1 },
            { id: 'e3', color: '#00ffff', position: 100, opacity: 1 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 0.4,
        visible: true,
        blurEnabled: true,
        blurAmount: 20,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'screen',
      },
      {
        name: 'Deep',
        type: 'gradient',
        gradient: {
          type: 'linear',
          angle: 225,
          stops: [
            { id: 'e4', color: '#1a2a6c', position: 0, opacity: 1 },
            { id: 'e5', color: '#b21f1f', position: 100, opacity: 1 },
          ],
          radialShape: 'circle',
          radialSize: 'farthest-corner',
          radialX: 50,
          radialY: 50,
          conicAngle: 0,
          conicX: 50,
          conicY: 50,
        },
        opacity: 1,
        visible: true,
        blurEnabled: false,
        blurAmount: 0,
        noiseEnabled: false,
        noiseAmount: 20,
        blendMode: 'normal',
      },
    ],
  },
];
